# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainFrom(object):
    def setupUi(self, MainFrom):
        MainFrom.setObjectName(_fromUtf8("MainFrom"))
        MainFrom.setEnabled(True)
        MainFrom.resize(521, 361)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainFrom.sizePolicy().hasHeightForWidth())
        MainFrom.setSizePolicy(sizePolicy)
        MainFrom.setMinimumSize(QtCore.QSize(521, 361))
        MainFrom.setMaximumSize(QtCore.QSize(521, 361))
        MainFrom.setAutoFillBackground(True)
        self.grbMain = QtGui.QGroupBox(MainFrom)
        self.grbMain.setGeometry(QtCore.QRect(10, 10, 501, 341))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grbMain.sizePolicy().hasHeightForWidth())
        self.grbMain.setSizePolicy(sizePolicy)
        self.grbMain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grbMain.setTitle(_fromUtf8(""))
        self.grbMain.setObjectName(_fromUtf8("grbMain"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.grbMain)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 481, 321))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.loadProgress = QtGui.QProgressBar(self.gridLayoutWidget_2)
        self.loadProgress.setProperty("value", 0)
        self.loadProgress.setTextVisible(False)
        self.loadProgress.setObjectName(_fromUtf8("loadProgress"))
        self.gridLayout_4.addWidget(self.loadProgress, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbSubject = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cmbSubject.setObjectName(_fromUtf8("cmbSubject"))
        self.gridLayout.addWidget(self.cmbSubject, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnClear = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.gridLayout_2.addWidget(self.btnClear, 1, 0, 1, 1)
        self.btnSubmit = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnSubmit.setObjectName(_fromUtf8("btnSubmit"))
        self.gridLayout_2.addWidget(self.btnSubmit, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 7, 1, 1, 1)
        self.lblRegion = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblRegion.setObjectName(_fromUtf8("lblRegion"))
        self.gridLayout.addWidget(self.lblRegion, 1, 0, 1, 1)
        self.lblSubject = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblSubject.setObjectName(_fromUtf8("lblSubject"))
        self.gridLayout.addWidget(self.lblSubject, 0, 0, 1, 1)
        self.cmbRegion = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cmbRegion.setObjectName(_fromUtf8("cmbRegion"))
        self.gridLayout.addWidget(self.cmbRegion, 1, 1, 1, 1)
        self.cmbCity = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cmbCity.setObjectName(_fromUtf8("cmbCity"))
        self.gridLayout.addWidget(self.cmbCity, 3, 1, 1, 1)
        self.lblCityType = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblCityType.setObjectName(_fromUtf8("lblCityType"))
        self.gridLayout.addWidget(self.lblCityType, 2, 0, 1, 1)
        self.lblCity = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblCity.setObjectName(_fromUtf8("lblCity"))
        self.gridLayout.addWidget(self.lblCity, 3, 0, 1, 1)
        self.cmbCityType = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cmbCityType.setObjectName(_fromUtf8("cmbCityType"))
        self.gridLayout.addWidget(self.cmbCityType, 2, 1, 1, 1)
        self.cmbStreetType = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.cmbStreetType.setObjectName(_fromUtf8("cmbStreetType"))
        self.gridLayout.addWidget(self.cmbStreetType, 4, 1, 1, 1)
        self.lblStreetType = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblStreetType.setObjectName(_fromUtf8("lblStreetType"))
        self.gridLayout.addWidget(self.lblStreetType, 4, 0, 1, 1)
        self.lblStreet = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblStreet.setObjectName(_fromUtf8("lblStreet"))
        self.gridLayout.addWidget(self.lblStreet, 5, 0, 1, 1)
        self.edtStreet = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.edtStreet.setAlignment(QtCore.Qt.AlignCenter)
        self.edtStreet.setObjectName(_fromUtf8("edtStreet"))
        self.gridLayout.addWidget(self.edtStreet, 5, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblBuilding = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblBuilding.setObjectName(_fromUtf8("lblBuilding"))
        self.gridLayout_3.addWidget(self.lblBuilding, 1, 0, 1, 1)
        self.edtApartment = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.edtApartment.setAlignment(QtCore.Qt.AlignCenter)
        self.edtApartment.setObjectName(_fromUtf8("edtApartment"))
        self.gridLayout_3.addWidget(self.edtApartment, 3, 1, 1, 1)
        self.lblApartment = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblApartment.setObjectName(_fromUtf8("lblApartment"))
        self.gridLayout_3.addWidget(self.lblApartment, 3, 0, 1, 1)
        self.edtBuilding = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.edtBuilding.setAlignment(QtCore.Qt.AlignCenter)
        self.edtBuilding.setObjectName(_fromUtf8("edtBuilding"))
        self.gridLayout_3.addWidget(self.edtBuilding, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.lblHouseNumber = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblHouseNumber.setObjectName(_fromUtf8("lblHouseNumber"))
        self.gridLayout_3.addWidget(self.lblHouseNumber, 0, 0, 1, 1)
        self.edtHouseNumber = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.edtHouseNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.edtHouseNumber.setObjectName(_fromUtf8("edtHouseNumber"))
        self.gridLayout_3.addWidget(self.edtHouseNumber, 0, 1, 1, 1)
        self.edtStructure = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.edtStructure.setAlignment(QtCore.Qt.AlignCenter)
        self.edtStructure.setObjectName(_fromUtf8("edtStructure"))
        self.gridLayout_3.addWidget(self.edtStructure, 2, 1, 1, 1)
        self.lblStructure = QtGui.QLabel(self.gridLayoutWidget_2)
        self.lblStructure.setObjectName(_fromUtf8("lblStructure"))
        self.gridLayout_3.addWidget(self.lblStructure, 2, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 6, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(MainFrom)
        QtCore.QMetaObject.connectSlotsByName(MainFrom)
        MainFrom.setTabOrder(self.cmbSubject, self.cmbRegion)
        MainFrom.setTabOrder(self.cmbRegion, self.cmbCityType)
        MainFrom.setTabOrder(self.cmbCityType, self.cmbCity)
        MainFrom.setTabOrder(self.cmbCity, self.cmbStreetType)
        MainFrom.setTabOrder(self.cmbStreetType, self.edtStreet)
        MainFrom.setTabOrder(self.edtStreet, self.edtHouseNumber)
        MainFrom.setTabOrder(self.edtHouseNumber, self.edtBuilding)
        MainFrom.setTabOrder(self.edtBuilding, self.edtStructure)
        MainFrom.setTabOrder(self.edtStructure, self.edtApartment)
        MainFrom.setTabOrder(self.edtApartment, self.btnSubmit)
        MainFrom.setTabOrder(self.btnSubmit, self.btnClear)

    def retranslateUi(self, MainFrom):
        MainFrom.setWindowTitle(_translate("MainFrom", "Справочная информация по объектам недвижимости", None))
        self.btnClear.setText(_translate("MainFrom", "Очистить", None))
        self.btnSubmit.setText(_translate("MainFrom", "Сформировать запрос", None))
        self.lblRegion.setText(_translate("MainFrom", "Район:", None))
        self.lblSubject.setText(_translate("MainFrom", "Субъект:", None))
        self.lblCityType.setText(_translate("MainFrom", "Тип населенного пункта:", None))
        self.lblCity.setText(_translate("MainFrom", "Населенный пункт:", None))
        self.lblStreetType.setText(_translate("MainFrom", "Тип улицы:", None))
        self.lblStreet.setText(_translate("MainFrom", "Улица:", None))
        self.lblBuilding.setText(_translate("MainFrom", "Корпус:", None))
        self.lblApartment.setText(_translate("MainFrom", "Номер квартиры:", None))
        self.lblHouseNumber.setText(_translate("MainFrom", "Номер дома:", None))
        self.lblStructure.setText(_translate("MainFrom", "Строение:", None))

